// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $AddTareas from "./routes/AddTareas.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_toggleCompleted from "./routes/api/toggleCompleted.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $main from "./routes/main.tsx";
import * as $register from "./routes/register.tsx";
import * as $Completado from "./islands/Completado.tsx";
import * as $Logout from "./islands/Logout.tsx";
import * as $Tarea from "./islands/Tarea.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/AddTareas.tsx": $AddTareas,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/toggleCompleted.ts": $api_toggleCompleted,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/main.tsx": $main,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/Completado.tsx": $Completado,
    "./islands/Logout.tsx": $Logout,
    "./islands/Tarea.tsx": $Tarea,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
